<#
.SYNOPSIS
    Update the API references.
#>



$ApiFolder = Join-Path -Path $PSScriptRoot -ChildPath "..", "docs", "api"

if (!(Test-Path $ApiFolder)) {
    throw "$ApiFolder is not exists"
    exit 1
}

# copy(Array.from(document.getElementsByClassName("jumplist")).map((i)=>"\""+i.childNodes[1].firstChild.href+"\"").join("\n,"))
$ApiLinks = @(
    "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.AspNetCore.Builder.McpEndpointRouteBuilderExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.HttpMcpServerBuilderExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.IMcpMessageFilterBuilder.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.IMcpRequestFilterBuilder.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.IMcpServerBuilder.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.McpAuthenticationExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.McpMessageFilterBuilderExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.McpRequestFilterBuilderExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.McpServerBuilderExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/Microsoft.Extensions.DependencyInjection.McpServerServiceCollectionExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AIContentExtensions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.IMcpTaskStore.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.InMemoryMcpTaskStore.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.McpErrorCode.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.McpException.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.McpJsonUtilities.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.McpProtocolException.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.McpSession.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.ProgressNotificationValue.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.RequestOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.UrlElicitationRequiredException.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Analyzers.CS1066Suppressor.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Analyzers.XmlToDescriptionGenerator.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.HttpServerTransportOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.ISessionMigrationHandler.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.Authentication.McpAuthenticationDefaults.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.Authentication.McpAuthenticationEvents.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.Authentication.McpAuthenticationHandler.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.Authentication.McpAuthenticationOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.AspNetCore.Authentication.ResourceMetadataRequestContext.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.AuthorizationRedirectDelegate.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.ClientOAuthOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.DynamicClientRegistrationOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.DynamicClientRegistrationResponse.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.ITokenCache.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.ProtectedResourceMetadata.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Authentication.TokenContainer.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.ClientCompletionDetails.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.HttpClientCompletionDetails.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.HttpClientTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.HttpClientTransportOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.HttpTransportMode.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.IClientTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClient.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientHandlers.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientPrompt.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientResource.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientResourceTemplate.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.McpClientTool.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.ResumeClientSessionOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.StdioClientCompletionDetails.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.StdioClientTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Client.StdioClientTransportOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Annotations.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Argument.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.AudioContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.BlobResourceContents.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CallToolMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CallToolRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CallToolResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CancelMcpTaskRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CancelMcpTaskResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CancelMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CancelledNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ClientCapabilities.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CompleteContext.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CompleteRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CompleteResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Completion.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CompletionsCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CreateElicitationMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CreateMessageMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CreateMessageRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CreateMessageResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.CreateTaskResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.BooleanSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.EnumSchemaOption.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.LegacyTitledEnumSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.NumberSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.PrimitiveSchemaDefinition.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.RequestSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.StringSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.TitledEnumItemsSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.TitledMultiSelectEnumSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.TitledSingleSelectEnumSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.UntitledEnumItemsSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.UntitledMultiSelectEnumSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitRequestParams.UntitledSingleSelectEnumSchema.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitResult-1.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitationCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitationCompleteNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ElicitationMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.EmbeddedResourceBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.EmptyResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.FormElicitationCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.GetPromptRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.GetPromptResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.GetTaskPayloadRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.GetTaskRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.GetTaskResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Icon.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ImageContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Implementation.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.InitializeRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.InitializeResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.InitializedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcError.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcErrorDetail.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcMessage.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcMessageContext.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcMessageWithId.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcNotification.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcRequest.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.JsonRpcResponse.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListPromptsRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListPromptsResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListResourceTemplatesRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListResourceTemplatesResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListResourcesRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListResourcesResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListRootsRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListRootsResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListTasksRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListTasksResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListToolsRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ListToolsResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.LoggingCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.LoggingMessageNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.McpTask.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.McpTaskMetadata.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.McpTaskStatusNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.McpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ModelHint.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ModelPreferences.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.NotificationMethods.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.NotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PaginatedRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PaginatedResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PingRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PingResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ProgressNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Prompt.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PromptArgument.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PromptListChangedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PromptMessage.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PromptReference.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.PromptsCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ReadResourceRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ReadResourceResult.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Reference.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RequestMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RequestMethods.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RequestParamsMetadata.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Resource.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceContents.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceLinkBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceListChangedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceTemplate.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceTemplateReference.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourceUpdatedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ResourcesCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Result.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Root.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RootsCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RootsListChangedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SamplingCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SamplingContextCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SamplingMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SamplingMessage.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SamplingToolsCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ServerCapabilities.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SetLevelRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.StreamClientTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.SubscribeRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.TextContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.TextResourceContents.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Tool.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolAnnotations.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolChoice.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolExecution.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolListChangedNotificationParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolResultContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolUseContentBlock.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolsCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolsMcpTasksCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.TransportBase.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.UnsubscribeRequestParams.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.UrlElicitationCapability.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.UrlElicitationRequiredErrorData.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ProgressToken.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.RequestId.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.IBaseMetadata.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ITransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ContextInclusion.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.LoggingLevel.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.McpTaskStatus.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.Role.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Protocol.ToolTaskSupport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.DelegatingMcpServerPrompt.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.DelegatingMcpServerResource.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.DelegatingMcpServerTool.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.DistributedCacheEventStreamStore.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.DistributedCacheEventStreamStoreOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpMessageFilters.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpMetaAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpRequestFilters.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServer.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerFilters.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerHandlers.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerPrimitiveCollection-1.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerPrompt.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerPromptAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerPromptCreateOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerPromptTypeAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerResource.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerResourceAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerResourceCollection.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerResourceCreateOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerResourceTypeAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerTool.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerToolAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerToolCreateOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpServerToolTypeAttribute.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.MessageContext.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.RequestContext-1.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.SseEventStreamOptions.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.SseResponseStreamTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.StdioServerTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.StreamServerTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.StreamableHttpServerTransport.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.IMcpServerPrimitive.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.ISseEventStreamReader.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.ISseEventStreamStore.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.ISseEventStreamWriter.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.SseEventStreamMode.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpMessageFilter.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpMessageHandler.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpRequestFilter-2.html"
    , "https://csharp.sdk.modelcontextprotocol.io/api/ModelContextProtocol.Server.McpRequestHandler-2.html"
)

$jobs = @()
for ($i = 0; $i -lt $ApiLinks.Count; $i++) {
    $link = $ApiLinks[$i]
    $urls = $link -split "/"
    $name = $urls[-1] -replace ".html", ".md"
    $path = Join-Path $ApiFolder $name
    Write-Host -ForegroundColor Yellow "[$($i+1)/$($ApiLinks.Count)] Downloading $link to $path"
    $job = Start-ThreadJob -ScriptBlock {
        param(
            $link,
            $path
        )
        $content = markitdown $link | Out-String
        $content = $content -replace '\[!\[MCP C# SDK\]\(\.\./images/mcp\.svg\)\r?\n', ""
        $content = $content -replace 'MCP C# SDK\]\(\.\./index\.html\)\r?\n', ""
        $content = $content -replace '\[Edit this page\]\(.*?\)\r?\n', ""
        $content = $content -replace 'Made with \[docfx\]\(https://dotnet\.github\.io/docfx\)', ""
        $content | Set-Content $path -Encoding utf8 -Force
    } -ArgumentList $link, $path -Name $name -ErrorAction Stop
    $jobs += $job
}

Write-Host -ForegroundColor Green "Waiting for all jobs to complete."
$jobs | ForEach-Object {
    $_ | Wait-Job
    if ($_.State -ne 'Completed') {
        Write-Host -ForegroundColor Red "Job $($_.Name) failed with state $($_.State)"
    }
    $_ | Receive-Job
}
$jobs | Remove-Job

Write-Host -ForegroundColor Green "Done."